// Code generated by Kitex v0.4.2. DO NOT EDIT.

package client_operations

import (
	api "ClyMQ/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Pub(ctx context.Context, req *api.PubRequest, callOptions ...callopt.Option) (r *api.PubResponse, err error)
	Pingpong(ctx context.Context, req *api.PingPongRequest, callOptions ...callopt.Option) (r *api.PingPongResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kClient_OperationsClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kClient_OperationsClient struct {
	*kClient
}

func (p *kClient_OperationsClient) Pub(ctx context.Context, req *api.PubRequest, callOptions ...callopt.Option) (r *api.PubResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Pub(ctx, req)
}

func (p *kClient_OperationsClient) Pingpong(ctx context.Context, req *api.PingPongRequest, callOptions ...callopt.Option) (r *api.PingPongResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Pingpong(ctx, req)
}
